### PR TITLE
Sipgate & terminate A leg on B leg failure

### LINKED ISSUE #15: sipgate requires their "sip id" in the From header of INVITEs sent to them
When a call is originated from Retell and we send it to a sipgate trunk, the From user will be the phone number/DID that was entered in Retell.  This usually works because that phone number is given by the carrier that we are sending the INVITE to.  Most carriers (Twilio is an example) will validate that the calling phone number is one of their numbers.

sipgate is different however.  They provide the customer with a "SIP-ID" which is a numeric string and that is what must appear in the From header.  Additionally, they support a Diversion header where you can put the actual calling number that you want to appear as the caller id.

Therefore, we should add a new environment variables:

- `OVERRIDE_FROM_USER`: if supplied, this value should appear as the `dial.callerId` on INVITEs sent to the SIP trunking provider (**note**: this should not change the behavior of INVITEs sent to Retell).

### LINKED ISSUE #16: failures on the B leg leave the caller hanging
The way the app is written, after the `dial` verb we have a `hangup` verb, intended to end the call.  However, since we are not answering the call before doing the dial, when the dial fails for any reason we proceed on to the hangup verb - but that has a precondition of an answered call and the call was never answered so it does nothing and the caller is hanging until they cancel.

We should implement an actionHook in the dial, and when we get a failure indication on that actionHook we should return a [sip:decline verb](https://docs.jambonz.org/verbs/verbs/sip-decline).

If, on the other hand, the actionHook is telling us the call is being ended normally after it was answered and the call is finished, then we return nothing from the actionHook and let the app continue towards the hangup.

### PR DESCRIPTION
**Pull request by sammachin**
closes #15 
closes #16

### CODE REVIEW

File: lib/routes/retell.js [hunk 1]
```diff
@@ -53,6 +56,11 @@ const service = ({logger, makeService}) => {
             trunk: process.env.PSTN_TRUNK_NAME
           }
         ];
+        /* Workaround for SIPGATE, put User ID as from and CLI in Diversion header */
+        if (OVERRIDE_FROM_USER) {
+          headers.Diversion = from;
```
Comment (davehorton) [inline lib/routes/retell.js:61]: Hmm, I thought the point was to put a "real" calling party number in the Diversion header so the person answering sees that as the caller id, while putting the sipgate sip-id in the from header

Comment (davehorton) [reply lib/routes/retell.js:61]: as I understand it, sipgate gives you a "SIP-ID" which is not a phone number yet which needs to the in the From header.  However, I dont think that is what should appear as a caller id to the party receiving the call, and that is what I thought the Diversion header was for.  This is sort of like how Voxbone used to work if I recall correctly

Comment (sammachin) [reply lib/routes/retell.js:61]: yes, but thats what this change will do, so you configure the app and retell all normally with your phone number
Then set the OVERIDE_FROM_USER env var to be your SIP-ID,
When a call comes from retell the from will be the phone number, this change will move that number to the Diversion header and set the from to be your SIP-ID

**Review by davehorton — APPROVED** [review]

**Comment by davehorton** [comment]
ready for merge @sammachin ?
